name = "Kishore Kumar SS"
rol = "Full Stack Developer"
email = "kishorekumarsskh@gmail.com"
phone = "+91 9566176890"
birthday = "December 16, 2004"
location = "Vellore, Tamil Nadu"
avatar = "./config/assets/avatars/my-avatar.png"
username = "kishorekumarss" # <-- github user name
presentation = """ I am Kishore Kumar SS, a Computer Science undergraduate at Vellore Institute of Technology (VIT) with a focus on technology. Currently serving as the Events Head of the IISE VIT Chapter, I excel in blending technical skills with leadership and organizational abilities. As a full-stack developer, I possess a strong foundation in both front-end and back-end technologies, with a focus on creating robust and user-friendly software solutions. My dedication to continuous learning and staying updated with the latest trends in technology.
"""
